name: Bugsfree Update Streams

on:
  schedule:
    - cron: '0 */8 * * *'
  workflow_dispatch:

jobs:
  update-streams:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install aiohttp requests
        
    - name: Run stream checker
      run: python convert_streams.py
      
    - name: Upload debug log
      uses: actions/upload-artifact@v3
      with:
        name: debug-log
        path: debug.log
        if-no-files-found: warn  # Add this to handle missing log gracefully
        
    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Update streams - $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
        git push
