name: Update LiveTV Links
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install ffmpeg-python requests
      - name: Run script
        run: python convert_m3u_to_hls.py
      - name: Debug directory contents
        run: ls -la iptv_hls_output/
      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add iptv_hls_output/*
          git commit -m "Update HLS streams and final M3U playlist" || echo "No changes to commit"
          git push
