name: TV-Brazil Update Files

on:
  schedule:
    - cron: '0 0,8,16 * * *'
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-files:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pytz beautifulsoup4

    - name: Run TV-Brazil M3U collector script
      run: python BugsfreeMain/TV-Brazil.py

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add LiveTV/Brazil/LiveTV.m3u LiveTV/Brazil/LiveTV.txt LiveTV/Brazil/LiveTV.json LiveTV/Brazil/LiveTV
        git commit -m "TV-Brazil Update files - $(date -u '+%Y-%m-%d %H:%M:%S UTC')" || echo "No changes to commit"
        git pull --rebase origin main
        git push
  # Existing content
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Your existing steps
      - name: Run TV-Brazil.py
        run: python LiveTV/TV-Brazil.py
      - name: Commit files
        run: |
          git add LiveTV/Brazil/*
          git commit -m "Update Brazil M3U and JSON"
          git push

# Add this to trigger index update
  update-indexes:
    needs: build
    uses: bugsfreeweb/LiveTVCollector/.github/workflows/update-indexes.yml@main
