name: TV-Italy Update Files

on:
  schedule:
    - cron: '0 0,8,16 * * *'
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-files:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pytz beautifulsoup4

    - name: Run TV-Italy M3U collector script
      run: python BugsfreeMain/TV-Italy.py

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add LiveTV/Italy/LiveTV.m3u LiveTV/Italy/LiveTV.txt LiveTV/Italy/LiveTV.json LiveTV/Italy/LiveTV
        git commit -m "TV-Italy Update files - $(date -u '+%Y-%m-%d %H:%M:%S UTC')" || echo "No changes to commit"
        git pull --rebase origin main
        git push
