name: Validate and Convert Streaming Links

on:
  schedule:
    - cron: "0 */8 * * *" # Run every 8 hours
  workflow_dispatch: # Allow manual trigger

jobs:
  process-links:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install requests

      - name: Run conversion script
        run: python convert_streaming_links.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add BugsfreeStreams/FinalStreamLinks.m3u
          git commit -m "Update FinalStreamLinks.m3u"
          git push
